IDX_TO_CATNAME_MAP = {0: 'Aluminium foil',
                      1: 'Battery',
                      2: 'Aluminium blister pack',
                      3: 'Carded blister pack',
                      4: 'Other plastic bottle',
                      5: 'Clear plastic bottle',
                      6: 'Glass bottle',
                      7: 'Plastic bottle cap',
                      8: 'Metal bottle cap',
                      9: 'Broken glass',
                      10: 'Food Can',
                      11: 'Aerosol',
                      12: 'Drink can',
                      13: 'Toilet tube',
                      14: 'Other carton',
                      15: 'Egg carton',
                      16: 'Drink carton',
                      17: 'Corrugated carton',
                      18: 'Meal carton',
                      19: 'Pizza box',
                      20: 'Paper cup',
                      21: 'Disposable plastic cup',
                      22: 'Foam cup',
                      23: 'Glass cup',
                      24: 'Other plastic cup',
                      25: 'Food waste',
                      26: 'Glass jar',
                      27: 'Plastic lid',
                      28: 'Metal lid',
                      29: 'Other plastic',
                      30: 'Magazine paper',
                      31: 'Tissues',
                      32: 'Wrapping paper',
                      33: 'Normal paper',
                      34: 'Paper bag',
                      35: 'Plastic film',
                      36: 'Six pack rings',
                      37: 'Garbage bag',
                      38: 'Other plastic wrapper',
                      39: 'Single-use carrier bag',
                      40: 'Polypropylene bag',
                      41: 'Crisp packet',
                      42: 'Spread tub',
                      43: 'Tupperware',
                      44: 'Disposable food container',
                      45: 'Foam food container',
                      46: 'Other plastic container',
                      47: 'Plastic glooves',
                      48: 'Plastic utensils',
                      49: 'Pop tab',
                      50: 'Rope & strings',
                      51: 'Scrap metal',
                      52: 'Shoe',
                      53: 'Squeezable tube',
                      54: 'Plastic straw',
                      55: 'Paper straw',
                      56: 'Styrofoam piece',
                      57: 'Unlabeled litter',
                      58: 'Cigarette'}

CATNAME_TO_IDX_MAP = {v: k for k, v in IDX_TO_CATNAME_MAP.items()}

IDX_TO_SUPERCATEGORY_MAP = {0: 'Bottle',
                            1: 'Carton',
                            2: 'Bottle cap',
                            3: 'Can',
                            4: 'Pop tab',
                            5: 'Cup',
                            6: 'Plastic bag & wrapper',
                            7: 'Styrofoam piece',
                            8: 'Other plastic',
                            9: 'Plastic container',
                            10: 'Paper',
                            11: 'Cigarette',
                            12: 'Lid',
                            13: 'Straw',
                            14: 'Paper bag',
                            15: 'Broken glass',
                            16: 'Plastic utensils',
                            17: 'Glass jar',
                            18: 'Food waste',
                            19: 'Squeezable tube',
                            20: 'Shoe',
                            21: 'Aluminium foil',
                            22: 'Unlabeled litter',
                            23: 'Blister pack',
                            24: 'Battery',
                            25: 'Rope & strings',
                            26: 'Scrap metal',
                            27: 'Plastic glooves'}
