# Utiliser une image Python officielle correspondant à votre version Python
FROM python:3.10.0-slim-buster

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers de dépendances et installer les packages
# Assurez-vous que api-requirements.txt est à la racine du contexte de build
COPY requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt

# Copier les dossiers nécessaires dans le conteneur
COPY src/category_utils.py /app/src/category_utils.py
COPY src/__init__.py /app/src/__init__.py
COPY src/detection /app/src/detection
COPY api /app/api
COPY api/main.py /app/main.py



# Exposer le port sur lequel l'API s'exécutera
EXPOSE 8080

# Commande pour lancer l'API
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
