CATIDX_2_EN_CATNAME = {0: 'Aluminium foil',
                       1: 'Battery',
                       2: 'Aluminium blister pack',
                       3: 'Carded blister pack',
                       4: 'Other plastic bottle',
                       5: 'Clear plastic bottle',
                       6: 'Glass bottle',
                       7: 'Plastic bottle cap',
                       8: 'Metal bottle cap',
                       9: 'Broken glass',
                       10: 'Food Can',
                       11: 'Aerosol',
                       12: 'Drink can',
                       13: 'Toilet tube',
                       14: 'Other carton',
                       15: 'Egg carton',
                       16: 'Drink carton',
                       17: 'Corrugated carton',
                       18: 'Meal carton',
                       19: 'Pizza box',
                       20: 'Paper cup',
                       21: 'Disposable plastic cup',
                       22: 'Foam cup',
                       23: 'Glass cup',
                       24: 'Other plastic cup',
                       25: 'Food waste',
                       26: 'Glass jar',
                       27: 'Plastic lid',
                       28: 'Metal lid',
                       29: 'Other plastic',
                       30: 'Magazine paper',
                       31: 'Tissues',
                       32: 'Wrapping paper',
                       33: 'Normal paper',
                       34: 'Paper bag',
                       35: 'Plastified paper bag',
                       36: 'Plastic film',
                       37: 'Six pack rings',
                       38: 'Garbage bag',
                       39: 'Other plastic wrapper',
                       40: 'Single-use carrier bag',
                       41: 'Polypropylene bag',
                       42: 'Crisp packet',
                       43: 'Spread tub',
                       44: 'Tupperware',
                       45: 'Disposable food container',
                       46: 'Foam food container',
                       47: 'Other plastic container',
                       48: 'Plastic glooves',
                       49: 'Plastic utensils',
                       50: 'Pop tab',
                       51: 'Rope & strings',
                       52: 'Scrap metal',
                       53: 'Shoe',
                       54: 'Squeezable tube',
                       55: 'Plastic straw',
                       56: 'Paper straw',
                       57: 'Styrofoam piece',
                       58: 'Unlabeled litter',
                       59: 'Cigarette',
                       60: 'Bin',
                       61: 'Underground container',
                       62: 'Mattress',
                       63: 'Bed complaint',
                       64: 'Sofa and armchair',
                       65: 'Furniture',
                       66: 'Table',
                       67: 'Chair',
                       68: 'Others furniture items',
                       69: 'Refrigerator',
                       70: 'Washing machine',
                       71: 'Oven',
                       72: 'Wood planks and other wood',
                       73: 'Wood pallet',
                       74: 'Screens',
                       75: 'Others electronic Equipment',
                       76: 'Metal waste',
                       77: 'Plastic buckets',
                       78: 'Gravats',
                       79: 'Christmas tree',
                       80: 'Graffiti',
                       81: 'Diffuse waste',
                       }

EN_CATNAME_2_CATIDX = {v: k for k, v in CATIDX_2_EN_CATNAME.items()}

EN_CATNAME_2_FR_CATNAME = {
    'Aluminium foil': "Papier d'aluminium",
    'Battery': 'Batterie',
    'Aluminium blister pack': 'Plaquette thermoformée en aluminium',
    'Carded blister pack': 'Plaquette thermoformée à carte',
    'Other plastic bottle': 'Autre bouteille en plastique',
    'Clear plastic bottle': 'Bouteille en plastique transparente',
    'Glass bottle': 'Bouteille en verre',
    'Plastic bottle cap': 'Bouchon de bouteille en plastique',
    'Metal bottle cap': 'Bouchon de bouteille en métal',
    'Broken glass': 'Verre brisé',
    'Food Can': 'Boîte de conserve',
    'Aerosol': 'Aérosol',
    'Drink can': 'Canette de boisson',
    'Toilet tube': 'Tube de papier toilette',
    'Other carton': 'Autre carton',
    'Egg carton': 'Boîte à œufs',
    'Drink carton': 'Brique de boisson',
    'Corrugated carton': 'Carton ondulé',
    'Meal carton': 'Boîte alimentaire en carton',
    'Pizza box': 'Boîte à pizza',
    'Paper cup': 'Gobelet en papier',
    'Disposable plastic cup': 'Gobelet en plastique jetable',
    'Foam cup': 'Gobelet en mousse',
    'Glass cup': 'Tasse en verre',
    'Other plastic cup': 'Autre gobelet en plastique',
    'Food waste': 'Déchets alimentaires',
    'Glass jar': 'Pot en verre',
    'Plastic lid': 'Couvercle en plastique',
    'Metal lid': 'Couvercle en métal',
    'Other plastic': 'Autre plastique',
    'Magazine paper': 'Papier de magazine',
    'Tissues': 'Mouchoirs',
    'Wrapping paper': 'Papier d\'emballage',
    'Normal paper': 'Papier ordinaire',
    'Paper bag': 'Sac en papier',
    'Plastified paper bag': 'Sac en papier plastifié',
    'Plastic film': 'Film plastique',
    'Six pack rings': 'Anneaux de canette',
    'Garbage bag': 'Sac poubelle',
    'Other plastic wrapper': 'Autre emballage en plastique',
    'Single-use carrier bag': 'Sac à usage unique',
    'Polypropylene bag': 'Sac en polypropylène',
    'Crisp packet': 'Paquet de chips',
    'Spread tub': 'Pot de tartinade',
    'Tupperware': 'Tupperware',
    'Disposable food container': 'Contenant alimentaire jetable',
    'Foam food container': 'Contenant alimentaire en mousse',
    'Other plastic container': 'Autre contenant en plastique',
    'Plastic glooves': 'Gants en plastique',
    'Plastic utensils': 'Ustensiles en plastique',
    'Pop tab': 'Onglet de canette',
    'Rope & strings': 'Corde et ficelles',
    'Scrap metal': 'Métal usagé',
    'Shoe': 'Chaussure',
    'Squeezable tube': 'Tube compressible',
    'Plastic straw': 'Paille en plastique',
    'Paper straw': 'Paille en papier',
    'Styrofoam piece': 'Morceau de polystyrène',
    'Unlabeled litter': 'Déchets non étiquetés',
    'Cigarette': 'Cigarette',
    'Bin': 'Poubelle',
    'Underground container': 'Conteneur enterré',
    'Mattress': 'Matelas',
    'Bed complaint': 'Sommier',
    'Sofa and armchair': 'Canapé et fauteuil',
    'Furniture': 'Meuble de rangement',
    'Table': 'Table',
    'Chair': 'Chaise',
    'Others furniture items': 'Autres meubles ou éléments de mobilier',
    'Refrigerator': 'Réfrigérateur',
    'Washing machine': 'Machine à laver',
    'Oven': 'Four',
    'Wood planks and other wood': 'Planches de bois et autres bois',
    'Wood pallet': 'Palette en bois',
    'Screens': 'Écrans',
    'Others electronic Equipment': 'Autres équipements électroniques',
    'Metal waste': 'Déchets métalliques',
    'Plastic buckets': 'Seaux en plastique',
    'Gravats': 'Gravats',
    'Christmas tree': 'Sapin de Noël',
    'Graffiti': 'Graffiti',
    'Diffuse waste': 'Déchets diffus',

}
FR_CATNAME_2_EN_CATNAME = {v: k for k, v in EN_CATNAME_2_FR_CATNAME.items()}

CATIDX_2_FR_CATNAME = {cat_idx: EN_CATNAME_2_FR_CATNAME[en_cat] for cat_idx, en_cat in CATIDX_2_EN_CATNAME.items()}
FR_CATNAME_2_CATIDX = {v: k for k, v in CATIDX_2_FR_CATNAME.items()}

CATIDX_2_EN_SUPERCATNAME = {0: 'Aluminium foil',
                            1: 'Battery',
                            2: 'Blister pack',
                            3: 'Blister pack',
                            4: 'Bottle',
                            5: 'Bottle',
                            6: 'Bottle',
                            7: 'Bottle cap',
                            8: 'Bottle cap',
                            9: 'Broken glass',
                            10: 'Can',
                            11: 'Can',
                            12: 'Can',
                            13: 'Carton',
                            14: 'Carton',
                            15: 'Carton',
                            16: 'Carton',
                            17: 'Carton',
                            18: 'Carton',
                            19: 'Carton',
                            20: 'Cup',
                            21: 'Cup',
                            22: 'Cup',
                            23: 'Cup',
                            24: 'Cup',
                            25: 'Food waste',
                            26: 'Glass jar',
                            27: 'Lid',
                            28: 'Lid',
                            29: 'Other plastic',
                            30: 'Paper',
                            31: 'Paper',
                            32: 'Paper',
                            33: 'Paper',
                            34: 'Paper bag',
                            35: 'Paper bag',
                            36: 'Plastic bag & wrapper',
                            37: 'Plastic bag & wrapper',
                            38: 'Plastic bag & wrapper',
                            39: 'Plastic bag & wrapper',
                            40: 'Plastic bag & wrapper',
                            41: 'Plastic bag & wrapper',
                            42: 'Plastic bag & wrapper',
                            43: 'Plastic container',
                            44: 'Plastic container',
                            45: 'Plastic container',
                            46: 'Plastic container',
                            47: 'Plastic container',
                            48: 'Plastic glooves',
                            49: 'Plastic utensils',
                            50: 'Pop tab',
                            51: 'Rope & strings',
                            52: 'Metal',
                            53: 'Shoe',
                            54: 'Squeezable tube',
                            55: 'Straw',
                            56: 'Straw',
                            57: 'Styrofoam piece',
                            58: 'Unlabeled litter',
                            59: 'Cigarette',
                            60: 'Trash Container',
                            61: 'Trash Container',
                            62: 'Large Household Item',
                            63: 'Large Household Item',
                            64: 'Large Household Item',
                            65: 'Large Household Item',
                            66: 'Large Household Item',
                            67: 'Large Household Item',
                            68: 'Large Household Item',
                            69: 'Home Appliance',
                            70: 'Home Appliance',
                            71: 'Home Appliance',
                            72: 'Wood',
                            73: 'Wood',
                            74: 'Electronic',
                            75: 'Electronic',
                            76: 'Metal',
                            77: 'Plastic container',
                            78: 'Gravats',
                            79: "Seasonal waste",
                            80: "Graffiti",
                            81: "Diffuse waste"
                            }

EN_CATNAME_2_EN_SUPERCATNAME = {catname: CATIDX_2_EN_SUPERCATNAME[catidx] for catidx, catname in
                                CATIDX_2_EN_CATNAME.items()}

SUPERCATIDX_2_EN_SUPERCATNAME = {0: 'Aluminium foil',
                                 1: 'Battery',
                                 2: 'Blister pack',
                                 3: 'Bottle',
                                 4: 'Bottle cap',
                                 5: 'Broken glass',
                                 6: 'Can',
                                 7: 'Carton',
                                 8: 'Cup',
                                 9: 'Food waste',
                                 10: 'Glass jar',
                                 11: 'Lid',
                                 12: 'Other plastic',
                                 13: 'Paper',
                                 14: 'Paper bag',
                                 15: 'Plastic bag & wrapper',
                                 16: 'Plastic container',
                                 17: 'Plastic glooves',
                                 18: 'Plastic utensils',
                                 19: 'Pop tab',
                                 20: 'Rope & strings',
                                 21: 'Metal',
                                 22: 'Shoe',
                                 23: 'Squeezable tube',
                                 24: 'Straw',
                                 25: 'Styrofoam piece',
                                 26: 'Unlabeled litter',
                                 27: 'Cigarette',
                                 28: 'Trash Container',
                                 29: 'Large Household Item',
                                 30: 'Home Appliance',
                                 31: 'Wood',
                                 32: 'Electronic',
                                 33: 'Gravats',
                                 34: "Seasonal waste",
                                 35: "Graffiti",
                                 36: "Diffuse waste"

                                 }

EN_SUPERCATNAME_2_SUPERCATIDX = {v: k for k, v in SUPERCATIDX_2_EN_SUPERCATNAME.items()}

EN_SUPERCATNAME_2_FR_SUPERCATNAME = {
    'Aluminium foil': 'Papier d\'aluminium',
    'Battery': 'Batterie',
    'Blister pack': 'Plaquette thermoformée',
    'Bottle': 'Bouteille',
    'Bottle cap': 'Bouchon de bouteille',
    'Broken glass': 'Verre brisé',
    'Can': 'Canette',
    'Carton': 'Carton',
    'Cup': 'Tasse',
    'Food waste': 'Déchets alimentaires',
    'Glass jar': 'Pot en verre',
    'Lid': 'Couvercle',
    'Other plastic': 'Autre plastique',
    'Paper': 'Papier',
    'Paper bag': 'Sac en papier',
    'Plastic bag & wrapper': 'Sac en plastique et emballage',
    'Plastic container': 'Conteneur en plastique',
    'Plastic glooves': 'Gants en plastique',
    'Plastic utensils': 'Ustensiles en plastique',
    'Pop tab': 'Onglet de canette',
    'Rope & strings': 'Corde et ficelles',
    'Scrap metal': 'Métal usagé',
    'Metal': 'Métal',
    'Shoe': 'Chaussure',
    'Squeezable tube': 'Tube compressible',
    'Straw': 'Paille',
    'Styrofoam piece': 'Morceau de polystyrène',
    'Unlabeled litter': 'Déchets non étiquetés',
    'Cigarette': 'Cigarette',
    'Trash Container': 'Conteneur à déchets',
    'Large Household Item': 'Gros objet ménager',
    'Home Appliance': 'Appareil électroménager',
    'Wood': 'Bois',
    'Electronic': 'Appareil électronique',
    'Gravats': 'Gravats',
    'Seasonal waste': 'Déchets saisonniers',
    'Graffiti': 'Graffiti',
    'Diffuse waste': 'Déchets diffus'
}

FR_SUPERCATNAME_2_EN_SUPERCATNAME = {v: k for k, v in EN_SUPERCATNAME_2_FR_SUPERCATNAME.items()}

CATIDX_2_FR_SUPERCATNAME = {cat_idx: EN_SUPERCATNAME_2_FR_SUPERCATNAME[en_cat] for cat_idx, en_cat in
                            CATIDX_2_EN_SUPERCATNAME.items()}

EN_CATNAME_2_EMOJI = {
    'Aluminium foil': '🔩',  # Since there's no specific emoji for aluminum foil, I used a metal-related emoji.
    'Battery': '🔋',
    'Aluminium blister pack': '💊',  # Represents medication, often packaged in blister packs.
    'Carded blister pack': '💊🃏',  # Combination of medication and card for the carded aspect.
    'Other plastic bottle': '🧴',
    'Clear plastic bottle': '🧴',
    'Glass bottle': '🍾',
    'Plastic bottle cap': '🔘',
    'Metal bottle cap': '🔘',
    'Broken glass': '🔨',  # A hammer to represent the breaking of glass.
    'Food Can': '🥫',
    'Aerosol': '🎨',  # Spray paint to represent aerosol.
    'Drink can': '🥤',
    'Toilet tube': '🧻',
    'Other carton': '📦',
    'Egg carton': '🥚📦',  # Eggs and a box to represent an egg carton.
    'Drink carton': '🧃',
    'Corrugated carton': '📦',
    'Meal carton': '🍱',
    'Pizza box': '🍕📦',
    'Paper cup': '🥤',
    'Disposable plastic cup': '🥤',
    'Foam cup': '☕',  # A hot beverage cup to represent a foam cup.
    'Glass cup': '🥃',
    'Other plastic cup': '🥤',
    'Food waste': '🍽️🗑️',  # A plate and a trash can to represent food waste.
    'Glass jar': '🍯',
    'Plastic lid': '🔘',
    'Metal lid': '🔘',
    'Other plastic': '♻️',  # Recycling symbol for general plastic.
    'Magazine paper': '📰',
    'Tissues': '🤧',
    'Wrapping paper': '🎁',
    'Normal paper': '📄',
    'Paper bag': '🛍️',
    'Plastified paper bag': '🛍️',
    'Plastic film': '♻️',
    'Six pack rings': '🍺',  # Beer emoji to represent six-pack rings.
    'Garbage bag': '💰🗑️',
    'Other plastic wrapper': '♻️',
    'Single-use carrier bag': '🛍️',
    'Polypropylene bag': '♻️',
    'Crisp packet': '🍿',  # Popcorn to represent snacks.
    'Spread tub': '🧈',  # Butter to represent spread.
    'Tupperware': '🥡',  # Takeout box to represent food storage.
    'Disposable food container': '🥡',
    'Foam food container': '🥡',
    'Other plastic container': '♻️',
    'Plastic glooves': '🧤',
    'Plastic utensils': '🍴',
    'Pop tab': '🥤',
    'Rope & strings': '🧵',  # A spool of thread to represent rope and strings.
    'Scrap metal': '🔩',
    'Shoe': '👟',
    'Squeezable tube': '🧴',  # A bottle to represent a squeezable tube.
    'Plastic straw': '🥤',
    'Paper straw': '🥤',
    'Styrofoam piece': '☕',
    'Unlabeled litter': '❓🗑️',  # A question mark and a trash can for unknown litter.
    'Cigarette': '🚬',
    'Bin': '🚮🗑️',
    'Underground container': '🗑️',
    'Mattress': '🛏️',
    'Bed complaint': '🛏️',
    'Sofa and armchair': '🛋️',
    'Furniture': '🛋️',
    'Table': '🪑',
    'Chair': '🪑',
    'Others furniture items': '🛋️',
    'Refrigerator': '🧊🗄️',
    'Washing machine': '🧺',
    'Oven': '🍕',
    'Wood planks and other wood': '🪵',
    'Wood pallet': '🪵',
    'Screens': '🖥️',
    'Others electronic Equipment': '🔌',
    'Metal': '🔩🔧',
    'Plastic buckets': '🪣',
    'Gravats': '🪨',
    'Christmas tree': '🎄',
    'Graffiti': '🎨',
    'Diffuse waste': '🗑️🍌🗺️'


}

CATIDX_2_EMOJI = {cat_idx: EN_CATNAME_2_EMOJI.get(en_cat, None) for cat_idx, en_cat in CATIDX_2_EN_CATNAME.items()}

EN_SUPERCATNAME_2_EMOJI = {
    'Aluminium foil': '🔩',
    'Battery': '🔋',
    'Blister pack': '💊',
    'Bottle': '🍾',
    'Bottle cap': '🔘',
    'Broken glass': '🔨',
    'Can': '🥫',
    'Carton': '📦',
    'Cup': '🥤',
    'Food waste': '🍽️🗑️',
    'Glass jar': '🍯',
    'Lid': '🔘',
    'Other plastic': '♻️',
    'Paper': '📄',
    'Paper bag': '🛍️',
    'Plastic bag & wrapper': '♻️',
    'Plastic container': '🥡',
    'Plastic glooves': '🧤',
    'Plastic utensils': '🍴',
    'Pop tab': '🥤',
    'Rope & strings': '🧵',
    'Scrap metal': '🔩',
    'Shoe': '👟',
    'Squeezable tube': '🧴',
    'Straw': '🥤',
    'Styrofoam piece': '☕',
    'Unlabeled litter': '❓🗑️',
    'Cigarette': '🚬'
}


# generate csv table [cat_idx, en_cat, fr_cat, en_super_cat, fr_super_cat, emoji]
def generate_table():
    import csv
    with open('../../__categories.csv', 'w', newline='', encoding='utf-8') as csvfile:
        fieldnames = ['cat_idx', 'en_cat', 'fr_cat', 'en_super_cat', 'fr_super_cat', 'emoji']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

        writer.writeheader()
        for cat_idx in range(60):
            writer.writerow({
                'cat_idx': cat_idx,
                'en_cat': CATIDX_2_EN_CATNAME[cat_idx],
                'fr_cat': CATIDX_2_FR_CATNAME[cat_idx],
                'en_super_cat': CATIDX_2_EN_SUPERCATNAME[cat_idx],
                'fr_super_cat': CATIDX_2_FR_SUPERCATNAME[cat_idx],
                'emoji': EN_CATNAME_2_EMOJI[CATIDX_2_EN_CATNAME[cat_idx]]
            })

    print('generate __categories.csv done')


if __name__ == '__main__':
    generate_table()
